sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  code_climate:
    repo_token: 83598ae1a16ff81da8cd506999202972ebbf9e88fd6a3cabcb0584403f802e91

language: node_js

node_js: stable

matrix:
  fast_finish: true
  allow_failures:
  - node_js: "4"

install:
  - npm install

branches:
  only: master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm run ci:travis
